SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab16.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "PID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "TOKEN" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "COMPANY_NAME" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "COMPANY_SHORTNAME" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "COMPANY_CELL" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "COMPANY_PHONE" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "COMPANY_URL" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "INTRO" 中的字符数据将被截断成大小为 "4000"。

SQL3132W  列 "TAXIS" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "ISBRANCH" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "LOGOURL" 中的字符数据将被截断成大小为 "250"。

SQL3105N  Export 实用程序已经完成导出 "11" 行。

