SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab113.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "NAME" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "IMAGEPATH" 中的字符数据将被截断成大小为 "90"。

SQL3132W  列 "POSITION" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "WIDTH" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "HEIGHT" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "UNDIAPHANEITY" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "QUALITY" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "DEPARTID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "3" 行。

