SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab141.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CONTENTID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "VIDEONAME" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "VIDEOURL" 中的字符数据将被截断成大小为 "4000"。

SQL3132W  列 "VIDEOCLASSIFY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TIME" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SPECIAL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "VIDEOREMARK" 中的字符数据将被截断成大小为 "1000"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "VIDEOCLASSIFYID" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

