SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab133.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CONTENTID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "IMAGE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "REMARK" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "URL_THUMB" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "PICTURECLASSIFYID" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

