SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab128.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "TITLE" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "INFORM_DETAIL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "INFORM_TYPE" 中的字符数据将被截断成大小为 "11"。

SQL3132W  列 "ENTIRONMENT_TYPE" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "ENTIRONMENT_NAME" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "URL" 中的字符数据将被截断成大小为 "150"。

SQL3132W  列 "IMG_URL" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

