SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab106.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "VIDEONAME" 中的字符数据将被截断成大小为 "225"。

SQL3132W  列 "REALNAME" 中的字符数据将被截断成大小为 "225"。

SQL3132W  列 "TRANSPATH" 中的字符数据将被截断成大小为 "300"。

SQL3132W  列 "LOCALPATH" 中的字符数据将被截断成大小为 "300"。

SQL3132W  列 "DEFAULTIMAGE" 中的字符数据将被截断成大小为 "300"。

SQL3132W  列 "TYPE" 中的字符数据将被截断成大小为 "10"。

SQL3132W  列 "MARK" 中的字符数据将被截断成大小为 "500"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "57" 行。

