SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab123.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CATID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "PATHIDS" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "MODELID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CLASSIFY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TITLE" 中的字符数据将被截断成大小为 "80"。

SQL3132W  列 "SUBTITLE" 中的字符数据将被截断成大小为 "120"。

SQL3132W  列 "THUMB" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TAGS" 中的字符数据将被截断成大小为 "60"。

SQL3132W  列 "AUTHOR" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "EDITOR" 中的字符数据将被截断成大小为 "15"。

SQL3132W  列 "SOURCEID" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "URL" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "STATUS" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CREATEDBY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "PUBLISHEDBY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "MODIFIEDBY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CHECKEDBY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "LOCKEDBY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "NOTEDBY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "WORKFLOW_ROLEID" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ISCONTRIBUTE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ALLOWCOMMENT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "DOCEXTENDJSON" 中的字符数据将被截断成大小为 "4000"。

SQL3132W  列 "DIGEST" 中的字符数据将被截断成大小为 "4000"。

SQL3132W  列 "ATTRIBUTE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CORRELATION" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "DESCRIPTION" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "CHANNELNAME" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "ISCOLLECT" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "PUBLISHEDBYID" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "LIST_THUMBNAIL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CONTENT_THUMBNAIL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SLIDE_THUMBNAIL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CONTENT_TYPE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TWO_CODE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CONTENT_MARK" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "RELEVANCEID" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

