SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab144.ixf"。

SQL3132W  列 "SCHEMA" 中的字符数据将被截断成大小为 "128"。

SQL3132W  列 "NAME" 中的字符数据将被截断成大小为 "128"。

SQL3132W  列 "STATS_FLAG" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "STATS_LOCK" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "SIGNAL" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "LEO_TAB" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "STATS_NOTIFY" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "STATS_DETAIL" 中的字符数据将被截断成大小为 "200"。

SQL3132W  列 "STATS_HISTORY" 中的字符数据将被截断成大小为 "200"。

SQL3132W  列 "REORG_FLAG" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "REORG_LOCK" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "REORG_NOTIFY" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "REORG_DETAIL" 中的字符数据将被截断成大小为 "200"。

SQL3132W  列 "REORG_HISTORY" 中的字符数据将被截断成大小为 "200"。

SQL3132W  列 "REORG_INDEX_SCHEMA" 中的字符数据将被截断成大小为 "128"。

SQL3132W  列 "REORG_INDEX_NAME" 中的字符数据将被截断成大小为 "128"。

SQL3132W  列 "REORG_INDEX_ONLINE" 中的字符数据将被截断成大小为 "1"。

SQL3105N  Export 实用程序已经完成导出 "300" 行。

