SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab13.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "ATTACHMENTTITLE" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "BUSINESSKEY" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "EXTEND" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "REALPATH" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "BUSENTITYNAME" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "INFOTYPEID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "USERID" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "13" 行。

