SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab155.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "WEIXIN_TITLE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "WEIXIN_DIGEST" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "WEIXIN_CONTENTADDRESS" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "WEIXIN_PICTUREURL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "WEIXIN_SORT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CONTENT_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "WEIXIN_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "WEIXIN_AUTHOR" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

