SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab110.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "VOTEID" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "OPTIONNAME" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "OPTIONLINK" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "OPTIONIMG" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "OPTIONSORT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "30" 行。

