SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab11.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "GID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "AD_NAME" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "CATEGORY" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "AD_CODE" 中的字符数据将被截断成大小为 "1000"。

SQL3132W  列 "IS_ENABLED" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "IMG_URL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "IHEIGHT" 中的字符数据将被截断成大小为 "30"。

SQL3132W  列 "IWEIGHT" 中的字符数据将被截断成大小为 "30"。

SQL3132W  列 "URLADRESS" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "URLPOINT" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "WORDCONTENT" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "WORDSIZE" 中的字符数据将被截断成大小为 "30"。

SQL3132W  列 "WORDCOLOR" 中的字符数据将被截断成大小为 "50"。

SQL3105N  Export 实用程序已经完成导出 "16" 行。

