SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab114.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CLIENT_ID" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CLIENT_SERCRET" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "REDIRECT_URI" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "BASEURL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ACCESSTOKENURL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "AUTHORIZEURL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "RMURL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ACCESSTOKEN" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "USERID" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

