SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab138.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CONTENTID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CUSTOM" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "PAGEBACKGROUND" 中的字符数据将被截断成大小为 "1000"。

SQL3132W  列 "RECIPIENT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SURVEYPEOLIMIT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SURVEYIPLIMIT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ISVIP" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "SURVEYID" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "4" 行。

