SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab111.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "SITEID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "WAPSTATUS" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "WAPNAME" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "WAPLOGO" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "INDEXCOLUMNCOUNT" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "INDEXMINWEIGHTS" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "COLUMNCOUNT" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "LISTCOUNT" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "COLUMNMINWEIGHTS" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "EVALUATELISTCOUNT" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "INDEXTEMPLATE" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "LISTTEMPLATE" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "CONTENTTEMPLATE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "PICTURESTEMPLATE" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "EVALUATETEMPLATE" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "VIDEO_TEMPLATE" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "SURVER_TEMPLATE" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "VOTE_TEMPLATE" 中的字符数据将被截断成大小为 "50"。

SQL3105N  Export 实用程序已经完成导出 "1" 行。

