SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab129.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "NAME" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "PATHIDS" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "PARENTID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "PARENTIDS" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CAT_ID" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CHANNEL_ICO" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CREATEDBY" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "MODIFIEDBY" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "WORKFLOWID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CHANNEL_TYPE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "PATH" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "URL" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "CONSTANTS" 中的字符数据将被截断成大小为 "11"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "21" 行。

