SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab119.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "TITLE" 中的字符数据将被截断成大小为 "16"。

SQL3132W  列 "CONNECT_URL" 中的字符数据将被截断成大小为 "160"。

SQL3132W  列 "CHANNELID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "BRIEF" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "IMG_URL" 中的字符数据将被截断成大小为 "160"。

SQL3132W  列 "SLIDE_URL" 中的字符数据将被截断成大小为 "160"。

SQL3132W  列 "CREATE_USER" 中的字符数据将被截断成大小为 "16"。

SQL3132W  列 "ISSUE_USER" 中的字符数据将被截断成大小为 "16"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

