SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab135.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "SPECIAL_NAME" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SPECIAL_THUB" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SPECIAL_CREATED" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SPECIAL_MARK" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SPECIAL_STATE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SPECIAL_TYPE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SPECIAL_SLIDE" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "2" 行。

