SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab126.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CONTENTS_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "INVITATION_TYPE" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "USER_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "USER_NAME" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "CONTACT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "REPLY_NAME" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "TITLE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "IP" 中的字符数据将被截断成大小为 "15"。

SQL3132W  列 "DISPLAY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "DISABLED" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "IMG" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CONTENTS_TITLE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CONTENTS_URL" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "38" 行。

