SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab116.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "RELATIONID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "AUDITINGROLE" 中的字符数据将被截断成大小为 "256"。

SQL3132W  列 "OPINION" 中的字符数据将被截断成大小为 "1024"。

SQL3132W  列 "AUDITOR" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "OPERATOROID" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "22" 行。

