SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab103.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "HEADADVRESOURCE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "HEADADVLINK" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "STOPADVREOURCE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "STOPADVLINK" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "FOOTADVRESOURCE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "FOOTADVLINK" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

