SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab19.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "MEMBERLEVEL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TITLE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "URL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CONTENT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "COLLECTPERSON" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "COLLECTPERSONID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CONTENTID" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "1" 行。

