SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab1.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CHANNEL_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "TYPE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "USER_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "ACQ_NAME" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "PAGE_ENCODING" 中的字符数据将被截断成大小为 "20"。

SQL3132W  列 "DYNAMIC_ADDR" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "LINKSET_START" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "LINKSET_END" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "LINK_START" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "LINK_END" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TITLE_START" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TITLE_END" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "KEYWORDS_START" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "KEYWORDS_END" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "DESCRIPTION_START" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "DESCRIPTION_END" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CONTENT_START" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CONTENT_END" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "PAGINATION_START" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "PAGINATION_END" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "REPEAT_CHECK_TYPE" 中的字符数据将被截断成大小为 "20"。

SQL3132W  列 "CONTENT_PREFIX" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "IMG_PREFIX" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "VIEW_START" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "VIEW_END" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "VIEW_ID_START" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "VIEW_ID_END" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "VIEW_LINK" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "RELEASETIME_START" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "RELEASETIME_END" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "AUTHOR_START" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "AUTHOR_END" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ORIGIN_START" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ORIGIN_END" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "RELEASETIME_FORMAT" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "1" 行。

