SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab20.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "USERNAME" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "MEMBERLEVEL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CONTENTID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "COMMENT_TYPE" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "TITLE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CONTENT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "COMMENTARYPERSON" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "PERSONID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "QQ" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CELLPHONE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TELEPHONE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ISCHECK" 中的字符数据将被截断成大小为 "10"。

SQL3105N  Export 实用程序已经完成导出 "10" 行。

