SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab28.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "WEBSITENAME" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "URIKEYWORDSFRAGMENT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "NESBODYTAG" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "NEWSBODYCLASS" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "NEWSBODYID" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "BEGINTAG" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ENDTAG" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SCHEME" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ATTRNAME" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ATTRVALUE" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "65" 行。

