SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab26.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "PARENTID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "PARENTIDS" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "PATHIDS" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "NAME" 中的字符数据将被截断成大小为 "20"。

SQL3132W  列 "ALIAS" 中的字符数据将被截断成大小为 "20"。

SQL3132W  列 "WORKFLOWID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "MODEL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TEMPLATE_INDEX" 中的字符数据将被截断成大小为 "2000"。

SQL3132W  列 "TEMPLATE_LIST" 中的字符数据将被截断成大小为 "2000"。

SQL3132W  列 "TEMPLATE_DATE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "PATH" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "THUMB" 中的字符数据将被截断成大小为 "60"。

SQL3132W  列 "WAP_URL" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "URL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "URLRULE_INDEX" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "URLRULE_LIST" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "URLRULE_SHOW" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "KEYWORDS" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "DESCRIPTION" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "EXTENDJSON" 中的字符数据将被截断成大小为 "4000"。

SQL3132W  列 "JSONID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "ISARTICLESELECTED" 中的字符数据将被截断成大小为 "200"。

SQL3132W  列 "CREATEDBY" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "MODIFIEDBY" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "INDEX_TEMPLATE" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "RSS_TEMPLATE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "MOBILECHANNEL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "STATIC_URL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "DYNAMIC_URL" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "51" 行。

