SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab2.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "TITLE" 中的字符数据将被截断成大小为 "150"。

SQL3132W  列 "SHORT_TITLE" 中的字符数据将被截断成大小为 "150"。

SQL3132W  列 "AUTHOR" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "ORIGIN" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "ORIGIN_URL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "DESCRIPTION" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "MEDIA_PATH" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "MEDIA_TYPE" 中的字符数据将被截断成大小为 "20"。

SQL3132W  列 "TITLE_COLOR" 中的字符数据将被截断成大小为 "10"。

SQL3132W  列 "TITLE_IMG" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "CONTENT_IMG" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "TYPE_IMG" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "LINK" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TPL_CONTENT" 中的字符数据将被截断成大小为 "100"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

