SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab48.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "FUNCTIONNAME" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "FUNCTIONORDER" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "FUNCTIONURL" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "PARENTFUNCTIONID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "ICONCLASS" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "PRIVURL" 中的字符数据将被截断成大小为 "1000"。

SQL3132W  列 "PATHIDS" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "PARENTIDS" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "80" 行。

