SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab44.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "APPROFILETYPE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "BUYPROJECTNO" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "BUYPROJECTORG" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "BUYUSE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "BUYYEAR" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CATEGORY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "COLLECTORG" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "EXPENSEACCOUNT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "MONEYAREA" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "MONEYSOURCE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "MONEYUSE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ZBWNO" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

