SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab57.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "PID" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "TOKEN" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "MAIL_PHONE" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "SMTP_ACCOUNT" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "SMTP_PASSWORD" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "MAIL_STAUTS" 中的字符数据将被截断成大小为 "250"。

SQL3105N  Export 实用程序已经完成导出 "2" 行。

