SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab51.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "INTERVIEW_ISSUE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "INTERVIEW_STATE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "INTERVIEW_INTRODUCE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "INTERVIEW_WAY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "INTERVIEW_PICTURE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "INTERVIEW_PLACE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "INTERVIEW_COMPERE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CUSTOM_MODEL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "NETFRIEND_SPEAK" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "VISITOR_SPEAK" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SPEAK_CHECK" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

