SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab52.ixf"。

SQL3132W  列 "GUESTID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "INTERVIEWID" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "GUEST_NAME" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "GUEST_URL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "GUEST_INTRODUCE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "GUEST_PICTURE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "GUEST_TOKEN" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

