SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab58.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "USERNAME" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "MEMBERLEVEL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "REALNAME" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "PASSWORD" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "REPASSWORD" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "FACEIMG" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "EMAIL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ADDRESS" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "QQ" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "CELLPHONE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TELEPHONE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "THIRDLOGIN_UID" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "THIRDTYPE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "THIRDTOKEN" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "MEMBERGROUPSID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CITYID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CITY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "NAME" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "MSN" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "REMARK" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "REGISTERIP" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "LOGIN_TYPE" 中的字符数据将被截断成大小为 "11"。

SQL3132W  列 "CARD_ID" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "CARD_PATH" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "19" 行。

