SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab63.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "MODEL_NAME" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "MODEL_PATH" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TPL_CHANNEL_PREFIX" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TPL_CONTENT_PREFIX" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "PRIORITY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "HAS_CONTENT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "IS_DISABLED" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "IS_DEF" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

