SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab69.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "OPERATIONCODE" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "OPERATIONICON" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "OPERATIONNAME" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "FUNCTIONID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "ICONID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "OPERATIONURL" 中的字符数据将被截断成大小为 "300"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

