SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab64.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "MODEL_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CHANNEL_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CONTENT_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "MODELITEM_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "ATTR_NAME" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "ATTR_VALUE" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "ATTR_TOKEN" 中的字符数据将被截断成大小为 "250"。

SQL3132W  列 "DATA_TYPE" 中的字符数据将被截断成大小为 "250"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

