SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab6.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CONTENTID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "ACTIVITYPLENUM" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ACTIVITYIPLIMIT" 中的字符数据将被截断成大小为 "11"。

SQL3132W  列 "ACTIVITYSEX" 中的字符数据将被截断成大小为 "11"。

SQL3132W  列 "ACTIVITYBACKGROUND" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ACTIVITYDATATYPE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ACTIVITYADDRESS" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ACTIVITYCONTENT" 中的字符数据将被截断成大小为 "1000"。

SQL3132W  列 "ACTIVITYREMARK" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ACTIVITYPEOPLE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ACTIVITYADDRESSPOINT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "2" 行。

