SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab65.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "MODEL_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "FIELD" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "ITEM_LABEL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "PRIORITY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "IS_SINGLE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "IS_DISPLAY" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "DEF_VALUE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "OPT_VALUE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TEXT_SIZE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "AREA_COLS" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "HELP" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "HELP_POSITION" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "IS_CHANNEL" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "IS_CUSTOM" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SITE_ID" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

