SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab7.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "OPTION_NAME" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "OPTION_MARK" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "DATE_TYPE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "TEXTSIZE_LIMIT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "OPTIONAL_VALUE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "VALIDATION" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "SORT" 中的字符数据将被截断成大小为 "11"。

SQL3132W  列 "SELECTSIZE_LIMIT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "FILESIZE_LIMIT" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "10" 行。

