SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab84.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CONFIG_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "FTP_UPLOAD_ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "DOMAIN" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "SITE_PATH" 中的字符数据将被截断成大小为 "20"。

SQL3132W  列 "SITE_NAME" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "SHORT_NAME" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "PROTOCOL" 中的字符数据将被截断成大小为 "20"。

SQL3132W  列 "DYNAMIC_SUFFIX" 中的字符数据将被截断成大小为 "10"。

SQL3132W  列 "STATIC_SUFFIX" 中的字符数据将被截断成大小为 "10"。

SQL3132W  列 "STATIC_DIR" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "IS_INDEX_TO_ROOT" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "IS_STATIC_INDEX" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "LOCALE_ADMIN" 中的字符数据将被截断成大小为 "10"。

SQL3132W  列 "LOCALE_FRONT" 中的字符数据将被截断成大小为 "10"。

SQL3132W  列 "TPL_SOLUTION" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "IS_RELATIVE_PATH" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "IS_RECYCLE_ON" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "DOMAIN_ALIAS" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "DOMAIN_REDIRECT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "INDEX_TEMPLATE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "IS_SWITCH" 中的字符数据将被截断成大小为 "10"。

SQL3105N  Export 实用程序已经完成导出 "2" 行。

