SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab97.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CREATE_BY" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CREATE_NAME" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "CRON_EXPRESSION" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "IS_EFFECT" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "IS_START" 中的字符数据将被截断成大小为 "1"。

SQL3132W  列 "TASK_DESCRIBE" 中的字符数据将被截断成大小为 "50"。

SQL3132W  列 "TASK_ID" 中的字符数据将被截断成大小为 "100"。

SQL3132W  列 "UPDATE_BY" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "UPDATE_NAME" 中的字符数据将被截断成大小为 "32"。

SQL3105N  Export 实用程序已经完成导出 "3" 行。

