SQL3104N  EXPORT 实用程序 正在开始将数据导出至文件 "tab9.ixf"。

SQL3132W  列 "ID" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "OPTIONDIDS" 中的字符数据将被截断成大小为 "32"。

SQL3132W  列 "EXT_TEXT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "IP" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "LOGIDS" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "EXT_CHECKBOX" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "EXT_SELECT" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "EXT_PICTURE" 中的字符数据将被截断成大小为 "255"。

SQL3132W  列 "EXT_FILE" 中的字符数据将被截断成大小为 "255"。

SQL3105N  Export 实用程序已经完成导出 "0" 行。

